### ISSUE TITLE
Request : Multiple accounts in sequence upload functions

### ISSUE THREAD

**Issue by jarlink1998** [JetBrains-CLion/YouTube-Upload-Bot#5]
Hi can you code for multiple account that in sequence of upload? for example if i have 100+ accounts i want each of the accounts upload 100 videos and so on. BTW that bot was awesome! glad i found this. Thanks for your effort and for sharing it!

**Comment by jarlink1998** [comment]
Hi can you code for multiple account that in sequence of upload? for example if i have 100+ accounts i want each of the accounts upload 100 videos and so on. BTW that bot was awesome! glad i found this

**Comment by zanelul** [comment]
Interesting request, will try to add that to the bot as an option. As for right now you have to just make copies of the bot and change the information then run it to work with multiple accounts.
