### ISSUE TITLE
Puppeteer doesn't work signing into google

### ISSUE THREAD

**Issue by eragonshadeslayer2030** [JetBrains-CLion/YouTube-Upload-Bot#7]
hello, when puppeteer tries signing into google it just says this 
![image](https://user-images.githubusercontent.com/50378203/189508262-c2db5786-0f59-44b4-9412-1c07aee29579.png)

**Comment by zanelul** [comment]
That is a bug, it will get fixed.

**Comment by eragonshadeslayer2030** [comment]
Cool, please reply to this message again when it does.

**Comment by zanelul** [comment]
Hello, just pushed my commit and it should be working now.
